# Generated by Django 3.2.18 on 2023-05-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('tanggal_publikasi', models.DateField()),
                ('Deskripsi', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='covers/')),
            ],
        ),
    ]
